### ISSUE TITLE
Multiple views demo broken

### ISSUE THREAD

**Issue by andygup** [odoe/presentations#6]
I haven't had a chance to clone the prezo yet, so I'm just gonna doc issues.

[https://odoe.github.io/presentations/2017-devsummit-dc-esrijs-whats-new/demos/architecture/multiple-views.html](https://odoe.github.io/presentations/2017-devsummit-dc-esrijs-whats-new/demos/architecture/multiple-views.html)

When I click the demo button I get an error `https://odoe.github.io/presentations/2017-devsummit-dc-esrijs-whats-new/demos/architecture/multiple-views.html`

**Comment by odoe** [comment]
demo has been fixed and moved to new location https://odoe.github.io/presentations/2017-devsummit-dc-esrijs-whats-new/demos/new/multiple-views.html

**Comment by codergrl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add GitGub](https://trello.com/c/SbpCnoJo/1-add-gitgub)
